### ISSUE TITLE
hide problem 

### ISSUE THREAD

**Issue by Akuye19** [huandney/Anki-Cloze-Interactive#5]
hello i really like this card type but when i create my own card i cant hide it the clozed word

**Comment by huandney** [comment]
Hi,
Can you send me the card in APKG format, so I can understand better?

**Comment by Akuye19** [comment]
thank you for your replu. here it is

28 Mar 2024 Per 05:08 tarihinde Huandney Ferreira Vaz <
***@***.***> şunu yazdı:

**Comment by Akuye19** [comment]
so is there any solution

**Comment by huandney** [comment]
I don't understand what the problem is, upload the card in question and send it to me.

**Comment by Akuye19** [comment]
check your e mail please i send it there. i can't send apgk files in here

**Comment by huandney** [comment]
I didn't receive the email, if you can upload it for example through Google drive and send the link here.

**Comment by Akuye19** [comment]
https://drive.google.com/file/d/1b-l7edlMod57XE9b_jLmBA_-F4L8J3x5/view?usp=drivesdk

i hope u can understand the problem now

**Comment by Akuye19** [comment]
can u see the issue now

**Comment by huandney** [comment]
I need authorization to access the file on the drive.

**Comment by Akuye19** [comment]
i hope u can make it

**Comment by huandney** [comment]
Which device does the problem occur on? If the card contains only one cloze, this is the default effect. After the last cloze is revealed, the script is closed, not allowing you to hide it again.

**Comment by Akuye19** [comment]
https://drive.google.com/file/d/1bbwirQdSIfghS77xSZmWPsCHBohrbGQA/view?usp=drivesdk

check this please

**Comment by huandney** [comment]
I don't understand what the problem is, can you be more detailed, and tell me which version and platform you are using.

**Comment by Akuye19** [comment]
the version is ankidroid 2.17.6 and i am using xioami note 10 pro im using

**Comment by huandney** [comment]
Have you configured User Action?
https://github.com/huandney/Anki-Cloze-Interactive?tab=readme-ov-file#user-actions-gestures-on-ankidroid-and-ankimobile

**Comment by Akuye19** [comment]
so my version is higher and yes i did the option as u said by the way when i add one more closed card in your interactive card type hide problem beginning at that card too. i cant hide the clozed card

**Comment by huandney** [comment]
Did you follow the steps below?
    1. Go to Settings.
    2. Navigate to Controls.
    3. Enable gestures
    4. Under User Actions, configure a preferred gesture. Set User Action 1 to reveal the next cloze and User Action 2 to hide the last revealed cloze.

**Comment by Akuye19** [comment]
i did it and still same thing. i think its all about the card type

**Comment by huandney** [comment]
I still don't understand the problem, are you unable to use the gestures? Can you explain better?

Analyzing the code I found a bug but this only concerns the function of turning the card back and rendering mathjax, I will soon post a correction.  It looks like it's not the error you're referring to.
