### ISSUE TITLE
autoFlip not working (AnkiDroid)

### ISSUE THREAD

**Issue by ravirpsc** [huandney/Anki-Cloze-Interactive#7]
I imported the .apkg in AnkiDroid and auto flip only works on the pre-made cards. I tried creating many cards with multiple clozes but no luck. Any possible solutions? Do I need to change anything from the script? I read in the ReadMe about some extra steps for it to work on AnkiMobile but AnkiDroid was not mentioned. I'm using AnkiDroid 2.18.4 on my Galaxy S20 FE and Xiaomi Tab 6.

**Comment by huandney** [comment]
Hi,
can you share the deck that isn't working?

**Comment by ravirpsc** [comment]
Yes, here is the deck:

[vocab (story-based).zip](https://github.com/user-attachments/files/17093903/vocab.story-based.zip)

I've added only a few cards to it since its a new template. And the only thing I changed is the text colour of cloze in dark mode. Everything else is original.

**Comment by huandney** [comment]
I just tested here, you are using an outdated version of the script, [version 1.3.1](https://raw.githubusercontent.com/huandney/Anki-Cloze-Interactive/refs/heads/main/card/front-template.html) fixed this bug.

**Comment by ravirpsc** [comment]
I updated the script and now it worked. I should have checked that myself, my bad. Thank you :)

**Comment by huandney** [comment]
No problem, if you have any questions, please don't hesitate to contact us.
